# Generated by Django 5.0.6 on 2024-06-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('second_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('monthly_salary', models.CharField(max_length=10000)),
            ],
        ),
    ]
